In [1]:
import torch

In [4]:
torch.backends.mps.is_available()

True

In [8]:
# Creating objects with differnt ranks

# 0D
tensor0d = torch.tensor(1)

# 1D from a list
tensor1d = torch.Tensor([1, 2, 3])

# 2D from a nested python list
tensor2d = torch.Tensor([[4, 5], [2, 5]])

# 3D
tensor3d = torch.Tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])



In [11]:
print(tensor2d.dtype)

torch.float32


In [13]:
# changing it to int with .to
intvec = tensor1d.to(torch.int64)
intvec.dtype

torch.int64

In [23]:
# Common tensor operations
tensor2d.shape

torch.Size([2, 2])

In [24]:
tensor2d

tensor([[4., 5.],
        [2., 5.]])

In [25]:
tensor2d.to(torch.int64)

tensor([[4, 5],
        [2, 5]])

In [ ]:
tensor2d.reshape(2,2)
# .view() can also be used

tensor([[4., 5.],
        [2., 5.]])

In [ ]:
# Transpose
tensor2d.T

tensor([[4., 2.],
        [5., 5.]])

In [28]:
# Multiplication

tensor2d.matmul(tensor2d.T)

tensor([[41., 33.],
        [33., 29.]])

In [29]:
# can also be multiplied with the @
tensor2d@tensor2d.T

tensor([[41., 33.],
        [33., 29.]])

In [31]:
# Logistic regression classifier

import torch.nn.functional as F

y = torch.tensor([1.0]) # true label
x1 = torch.Tensor([1.1]) # infput feature
w1 = torch.Tensor([2.2]) # weight parameter
b = torch.tensor([0.0]) # bias unit

z = x1 * w1 + b # net input
a = torch.sigmoid(z) # activation and output

loss = F.binary_cross_entropy(a,y)
print(loss)

tensor(0.0852)


In [58]:
# Using the autograd engine

from torch.autograd import grad

y = torch.tensor([1.0]) # true label
x1 = torch.tensor([1.1]) # infput feature
w1 = torch.tensor([2.2], requires_grad=True) # weight parameter
b = torch.tensor([0.0], requires_grad=True) # bias unit

z = x1 * w1 + b # net input
a = torch.sigmoid(z) # activation and output

loss = F.binary_cross_entropy(a,y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)
print(grad_L_b)
print(grad_L_w1)

(tensor([-0.0817]),)
(tensor([-0.0898]),)


In [59]:
# using high level .backward

loss.backward()



In [60]:
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


In [63]:
# Creating a multilayer perceptron neural network

class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(

            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # output layer
            torch.nn.Linear(20, num_outputs),
        )
    
    def forward(self, x):
        logits = self.layers(x)
        return logits


In [78]:
torch.manual_seed(123) # to make things reproducible with the tutorial

model = NeuralNetwork(50, 3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [79]:
# Checking the number of trainable parameters in the model

num_params = sum(
    p.numel() for p in model.parameters() if p.requires_grad
)
print("Total number of trainable model parameters:", num_params)



Total number of trainable model parameters: 2213


In [80]:
# CHecking out the weight parameter matrix of the first linear layer:

print(model.layers[0].weight) # can also use .shape

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [81]:
# Accessing the bias vector

model.layers[0].bias

Parameter containing:
tensor([-0.1250,  0.0513,  0.0366,  0.0075,  0.0509,  0.0545, -0.0393,  0.0924,
        -0.1412, -0.1232, -0.1063,  0.0081, -0.1249,  0.0101, -0.0019, -0.1298,
         0.1388, -0.0330,  0.1017,  0.1247, -0.0554, -0.0417,  0.1388,  0.0159,
         0.1215,  0.0385,  0.0769, -0.1224, -0.0279,  0.0991],
       requires_grad=True)