In [1]:
import torch

In [4]:
torch.backends.mps.is_available()

True

In [8]:
# Creating objects with differnt ranks

# 0D
tensor0d = torch.tensor(1)

# 1D from a list
tensor1d = torch.Tensor([1, 2, 3])

# 2D from a nested python list
tensor2d = torch.Tensor([[4, 5], [2, 5]])

# 3D
tensor3d = torch.Tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])



In [11]:
print(tensor2d.dtype)

torch.float32


In [13]:
# changing it to int with .to
intvec = tensor1d.to(torch.int64)
intvec.dtype

torch.int64

In [23]:
# Common tensor operations
tensor2d.shape

torch.Size([2, 2])

In [24]:
tensor2d

tensor([[4., 5.],
        [2., 5.]])

In [25]:
tensor2d.to(torch.int64)

tensor([[4, 5],
        [2, 5]])

In [ ]:
tensor2d.reshape(2,2)
# .view() can also be used

tensor([[4., 5.],
        [2., 5.]])

In [ ]:
# Transpose
tensor2d.T

tensor([[4., 2.],
        [5., 5.]])

In [28]:
# Multiplication

tensor2d.matmul(tensor2d.T)

tensor([[41., 33.],
        [33., 29.]])